-- Indices
-- Paciente
CREATE UNIQUE INDEX PRIMARIO_PACIENTE ON paciente(IDPACIENTE);
CREATE UNIQUE INDEX RFC ON paciente(RFC);
CREATE INDEX SECUNDARIO_PACIENTE ON paciente(SEXO,FECHA_ALTA,ESTATUS);

-- Telefono
CREATE UNIQUE INDEX PRIMARIO_TELEFONO ON telefono(IDTELEFONO);
CREATE UNIQUE INDEX TELEFONOS ON telefono(TELEFONO);

-- Factura
CREATE INDEX FECHAS_FACTURA ON factura(FECHA);

-- Ocupacion
CREATE UNIQUE INDEX PRIMARIO_OCUPACION ON OCUPACION(IDOCUPACION);
CREATE INDEX NOMBRE_OCUPACION ON OCUPACION(NOMBRE_OCUPACION);

-- Colonia
CREATE UNIQUE INDEX PRIMARIO_COLONIA ON COLONIA(IDCOLONIA);
CREATE INDEX NOMBRE_COLONIA ON COLONIA(NOMBRE_COLONIA);

-- Poblacion
CREATE UNIQUE INDEX PRIMARIO_POBLACION ON POBLACION(IDPOBLACION);
CREATE INDEX NOMBRE_POBLACION ON POBLACION(NOMBRE_POBLACION);

-- Municipio
CREATE UNIQUE INDEX PRIMARIO_MUNICIPIO ON MUNICIPIO(IDMUNICIPIO);
CREATE INDEX NOMBRE_MUNICIPIO ON MUNICIPIO(NOMBRE_MUNICIPIO);

-- Estado
CREATE UNIQUE INDEX PRIMARIO_ESTADO ON ESTADO(IDESTADO);
CREATE INDEX NOMBRE_ESTADO ON ESTADO(NOMBRE_ESTADO);

-- Cita
CREATE UNIQUE INDEX PRIMARIO_CITA ON CITA(IDCITA);
CREATE INDEX FECHA_CITA ON CITA(FECHA_CITA);

-- Cita_Estudio
CREATE INDEX ID_CITA ON CITA_ESTUDIO(IDCITA);
CREATE INDEX ID_ESTUDIO ON CITA_ESTUDIO(IDESTUDIO);

-- Cita_Medicamento_nuevo
CREATE INDEX ID_CITA_MEDICAMENTO_NUEVO ON CITA_MEDICAMENTO_NUEVO(IDCITA);
CREATE INDEX ID_MEDICAMENTO_NUEVO ON CITA_MEDICAMENTO_NUEVO(IDMEDICAMENTO);

-- Cita_Medicamento_anterior
CREATE INDEX ID_CITA_MEDICAMENTO_ANTERIOR ON CITA_MEDICAMENTO_ANTERIOR(IDCITA);
CREATE INDEX ID_MEDICAMENTO_ANTERIOR ON CITA_MEDICAMENTO_ANTERIOR(IDMEDICAMENTO);

-- Estudio
CREATE UNIQUE INDEX PRIMARIO_ESTUDIO ON ESTUDIO(IDESTUDIO);
CREATE INDEX ESTUDIO ON ESTUDIO(NOMBRE_ESTUDIO);

-- Medicamento
CREATE UNIQUE INDEX PRIMARIO_MEDICAMENTO ON MEDICAMENTO(IDMEDICAMENTO);
CREATE INDEX MEDICAMENTO ON MEDICAMENTO(NOMBRE);