/*
SQLyog Community v13.1.5  (64 bit)
MySQL - 5.7.28-log : Database - bd_medico
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`bd_medico` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `bd_medico`;

/*Table structure for table `cita` */

DROP TABLE IF EXISTS `cita`;

CREATE TABLE `cita` (
  `IDCITA` int(11) NOT NULL AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA',
  `IDPACIENTE` int(11) NOT NULL,
  `FECHA_CITA` date NOT NULL COMMENT 'FECHA DE LA CITA',
  `SINTOMAS` varchar(100) NOT NULL COMMENT 'SINTOMAS QUE PRESENTA EL PACIENTE',
  `DIAGNOSTICO` varchar(100) DEFAULT NULL COMMENT 'DIAGNOSTICO DEL MEDICO, PUEDE ESTAR VACIO PORQUE SE GENERA EN UNA CITA POSTERIOR',
  `FECHA_DIAGNOSTICO` date DEFAULT NULL COMMENT 'FECHA DEL DIAGNOSTICO',
  `FECHA_PROX_CITA` date DEFAULT '1900-01-01' COMMENT 'FECHA DE LA PROXIMA CITA, PUEDE QUEDAR VACIA',
  `PAGO` int(11) DEFAULT '0' COMMENT 'MONTO PAGADO POR EL PACIENTE',
  `PRESION_ARTERIAL` varchar(7) DEFAULT '000/000' COMMENT 'PRESION ARTERIAL',
  `TEMPERATURA` int(11) DEFAULT '0' COMMENT 'TEMPERATURA',
  `OXIGENACION` int(11) DEFAULT '0' COMMENT 'OXIGENACION',
  `PESO` float DEFAULT '0' COMMENT 'PESO EN KILOGRAMOS',
  PRIMARY KEY (`IDCITA`),
  UNIQUE KEY `PRIMARIO_CITA` (`IDCITA`),
  KEY `fk_CITA_PACIENTE1_idx` (`IDPACIENTE`),
  KEY `FECHA_CITA` (`FECHA_CITA`),
  CONSTRAINT `fk_CITA_PACIENTE1` FOREIGN KEY (`IDPACIENTE`) REFERENCES `paciente` (`IDPACIENTE`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `cita` */

/*Table structure for table `cita_estudio` */

DROP TABLE IF EXISTS `cita_estudio`;

CREATE TABLE `cita_estudio` (
  `IDCITA` int(11) NOT NULL,
  `IDESTUDIO` int(11) NOT NULL,
  KEY `fk_CITA_has_ESTUDIO_ESTUDIO1_idx` (`IDESTUDIO`),
  KEY `fk_CITA_has_ESTUDIO_CITA1_idx` (`IDCITA`),
  KEY `ID_CITA` (`IDCITA`),
  KEY `ID_ESTUDIO` (`IDESTUDIO`),
  CONSTRAINT `fk_CITA_has_ESTUDIO_CITA1` FOREIGN KEY (`IDCITA`) REFERENCES `cita` (`IDCITA`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CITA_has_ESTUDIO_ESTUDIO1` FOREIGN KEY (`IDESTUDIO`) REFERENCES `estudio` (`IDESTUDIO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `cita_estudio` */

/*Table structure for table `cita_medicamento_anterior` */

DROP TABLE IF EXISTS `cita_medicamento_anterior`;

CREATE TABLE `cita_medicamento_anterior` (
  `IDCITA` int(11) NOT NULL,
  `IDMEDICAMENTO` int(11) NOT NULL,
  KEY `fk_CITA_has_MEDICAMENTO_MEDICAMENTO2_idx` (`IDMEDICAMENTO`),
  KEY `fk_CITA_has_MEDICAMENTO_CITA2_idx` (`IDCITA`),
  KEY `ID_CITA_MEDICAMENTO_ANTERIOR` (`IDCITA`),
  KEY `ID_MEDICAMENTO_ANTERIOR` (`IDMEDICAMENTO`),
  CONSTRAINT `fk_CITA_has_MEDICAMENTO_CITA2` FOREIGN KEY (`IDCITA`) REFERENCES `cita` (`IDCITA`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CITA_has_MEDICAMENTO_MEDICAMENTO2` FOREIGN KEY (`IDMEDICAMENTO`) REFERENCES `medicamento` (`IDMEDICAMENTO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `cita_medicamento_anterior` */

/*Table structure for table `cita_medicamento_nuevo` */

DROP TABLE IF EXISTS `cita_medicamento_nuevo`;

CREATE TABLE `cita_medicamento_nuevo` (
  `IDCITA` int(11) NOT NULL,
  `IDMEDICAMENTO` int(11) NOT NULL,
  KEY `fk_CITA_has_MEDICAMENTO_MEDICAMENTO1_idx` (`IDMEDICAMENTO`),
  KEY `fk_CITA_has_MEDICAMENTO_CITA1_idx` (`IDCITA`),
  KEY `ID_CITA_MEDICAMENTO_NUEVO` (`IDCITA`),
  KEY `ID_MEDICAMENTO_NUEVO` (`IDMEDICAMENTO`),
  CONSTRAINT `fk_CITA_has_MEDICAMENTO_CITA1` FOREIGN KEY (`IDCITA`) REFERENCES `cita` (`IDCITA`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CITA_has_MEDICAMENTO_MEDICAMENTO1` FOREIGN KEY (`IDMEDICAMENTO`) REFERENCES `medicamento` (`IDMEDICAMENTO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `cita_medicamento_nuevo` */

/*Table structure for table `colonia` */

DROP TABLE IF EXISTS `colonia`;

CREATE TABLE `colonia` (
  `IDCOLONIA` int(11) NOT NULL AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DE LA TABLA',
  `NOMBRE_COLONIA` varchar(100) NOT NULL COMMENT 'NOMBRE DE LA COLONIA',
  PRIMARY KEY (`IDCOLONIA`),
  UNIQUE KEY `PRIMARIO_COLONIA` (`IDCOLONIA`),
  KEY `NOMBRE_COLONIA` (`NOMBRE_COLONIA`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

/*Data for the table `colonia` */

insert  into `colonia`(`IDCOLONIA`,`NOMBRE_COLONIA`) values 
(3,'Centro'),
(1,'Dr. Miguel Silva'),
(2,'Realito');

/*Table structure for table `estado` */

DROP TABLE IF EXISTS `estado`;

CREATE TABLE `estado` (
  `IDESTADO` int(11) NOT NULL AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DE LA TABLA',
  `NOMBRE_ESTADO` varchar(30) NOT NULL COMMENT 'NOMBRE DEL ESTADO',
  PRIMARY KEY (`IDESTADO`),
  UNIQUE KEY `PRIMARIO_ESTADO` (`IDESTADO`),
  KEY `NOMBRE_ESTADO` (`NOMBRE_ESTADO`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8;

/*Data for the table `estado` */

insert  into `estado`(`IDESTADO`,`NOMBRE_ESTADO`) values 
(1,'CDMX'),
(10,'Chiapas'),
(4,'Colima'),
(9,'Cuahuila'),
(5,'Durango'),
(2,'Jalisco'),
(8,'Michoacan'),
(3,'Queretaro'),
(11,'Sinaloa'),
(6,'Yucatan'),
(7,'Zacatecas');

/*Table structure for table `estudio` */

DROP TABLE IF EXISTS `estudio`;

CREATE TABLE `estudio` (
  `IDESTUDIO` int(11) NOT NULL AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA',
  `NOMBRE_ESTUDIO` varchar(100) NOT NULL COMMENT 'NOMBRE DEL ESTUDIO',
  PRIMARY KEY (`IDESTUDIO`),
  UNIQUE KEY `PRIMARIO_ESTUDIO` (`IDESTUDIO`),
  KEY `ESTUDIO` (`NOMBRE_ESTUDIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `estudio` */

/*Table structure for table `factura` */

DROP TABLE IF EXISTS `factura`;

CREATE TABLE `factura` (
  `IDFACTURA` int(11) NOT NULL COMMENT 'CORRESPONDE AL FOLIO DE LA FACTURA, NO ES AUTOINCREMENTABLE Y SE PUEDE REPETIR, YA QUE CADA AÑO SE PUEDE REINICIAR',
  `FECHA` date NOT NULL COMMENT 'FECHA DE EXPEDICION DE LA FACTURA',
  `IDPACIENTE` int(11) NOT NULL,
  KEY `fk_FACTURA_PACIENTE1_idx` (`IDPACIENTE`),
  KEY `FECHAS_FACTURA` (`FECHA`),
  CONSTRAINT `fk_FACTURA_PACIENTE1` FOREIGN KEY (`IDPACIENTE`) REFERENCES `paciente` (`IDPACIENTE`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `factura` */

/*Table structure for table `medicamento` */

DROP TABLE IF EXISTS `medicamento`;

CREATE TABLE `medicamento` (
  `IDMEDICAMENTO` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(100) NOT NULL COMMENT 'NOMBRE DEL MEDICAMENTO',
  PRIMARY KEY (`IDMEDICAMENTO`),
  UNIQUE KEY `PRIMARIO_MEDICAMENTO` (`IDMEDICAMENTO`),
  KEY `MEDICAMENTO` (`NOMBRE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `medicamento` */

/*Table structure for table `municipio` */

DROP TABLE IF EXISTS `municipio`;

CREATE TABLE `municipio` (
  `IDMUNICIPIO` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE_MUNICIPIO` varchar(50) NOT NULL COMMENT 'NOMBRE DEL MUNICIPIO',
  PRIMARY KEY (`IDMUNICIPIO`),
  UNIQUE KEY `PRIMARIO_MUNICIPIO` (`IDMUNICIPIO`),
  KEY `NOMBRE_MUNICIPIO` (`NOMBRE_MUNICIPIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `municipio` */

/*Table structure for table `ocupacion` */

DROP TABLE IF EXISTS `ocupacion`;

CREATE TABLE `ocupacion` (
  `IDOCUPACION` int(11) NOT NULL AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DE LA TABLA',
  `NOMBRE_OCUPACION` varchar(50) NOT NULL COMMENT 'OCUPACION',
  PRIMARY KEY (`IDOCUPACION`),
  UNIQUE KEY `PRIMARIO_OCUPACION` (`IDOCUPACION`),
  KEY `NOMBRE_OCUPACION` (`NOMBRE_OCUPACION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `ocupacion` */

/*Table structure for table `paciente` */

DROP TABLE IF EXISTS `paciente`;

CREATE TABLE `paciente` (
  `IDPACIENTE` int(11) NOT NULL AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA',
  `NOMBRES` varchar(30) NOT NULL COMMENT 'NOMBRES DEL PACIENTE',
  `APATERNO` varchar(20) NOT NULL COMMENT 'APELLIDO PATERNO',
  `AMATERNO` varchar(20) NOT NULL COMMENT 'APELLIDO MATERNO',
  `CALLE` varchar(100) NOT NULL COMMENT 'CALLE',
  `NUMERO` int(11) NOT NULL COMMENT 'NUMERO EXTERIOR',
  `FECHA_NACIMIENTO` date NOT NULL DEFAULT '1900-01-01' COMMENT 'FECHA DE NACIMIENTO',
  `SEXO` char(1) NOT NULL COMMENT 'SEXO, M=MASCULINO, F=FEMENINO',
  `EMAIL` varchar(100) DEFAULT 'correo@algo.com' COMMENT 'CORREO ELECTRONICO',
  `RFC` varchar(13) DEFAULT 'ALGO000000XXX' COMMENT 'RFC',
  `FECHA_ALTA` date NOT NULL COMMENT 'FECHA DE ALTA COMO PACIENTE DEL MEDICO',
  `ESTATUS` char(1) NOT NULL DEFAULT 'A' COMMENT 'ESTATUS DEL PACIENTE, A=ACTIVO, I=INACTIVO',
  `IDPOBLACION` int(11) NOT NULL,
  `IDMUNICIPIO` int(11) NOT NULL,
  `IDESTADO` int(11) NOT NULL,
  `IDOCUPACION` int(11) NOT NULL,
  `IDTIPO_PACIENTE` int(11) NOT NULL,
  `IDCOLONIA` int(11) NOT NULL,
  PRIMARY KEY (`IDPACIENTE`),
  UNIQUE KEY `PRIMARIO_PACIENTE` (`IDPACIENTE`),
  UNIQUE KEY `RFC` (`RFC`),
  KEY `fk_PACIENTE_POBLACION1_idx` (`IDPOBLACION`),
  KEY `fk_PACIENTE_MUNICIPIO1_idx` (`IDMUNICIPIO`),
  KEY `fk_PACIENTE_ESTADO1_idx` (`IDESTADO`),
  KEY `fk_PACIENTE_OCUPACION1_idx` (`IDOCUPACION`),
  KEY `fk_PACIENTE_TIPO_PACIENTE1_idx` (`IDTIPO_PACIENTE`),
  KEY `fk_PACIENTE_COLONIA1_idx` (`IDCOLONIA`),
  KEY `SECUNDARIO_PACIENTE` (`SEXO`,`FECHA_ALTA`,`ESTATUS`),
  CONSTRAINT `fk_PACIENTE_COLONIA1` FOREIGN KEY (`IDCOLONIA`) REFERENCES `colonia` (`IDCOLONIA`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_PACIENTE_ESTADO1` FOREIGN KEY (`IDESTADO`) REFERENCES `estado` (`IDESTADO`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_PACIENTE_MUNICIPIO1` FOREIGN KEY (`IDMUNICIPIO`) REFERENCES `municipio` (`IDMUNICIPIO`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_PACIENTE_OCUPACION1` FOREIGN KEY (`IDOCUPACION`) REFERENCES `ocupacion` (`IDOCUPACION`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_PACIENTE_POBLACION1` FOREIGN KEY (`IDPOBLACION`) REFERENCES `poblacion` (`IDPOBLACION`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_PACIENTE_TIPO_PACIENTE1` FOREIGN KEY (`IDTIPO_PACIENTE`) REFERENCES `tipo_paciente` (`IDTIPO_PACIENTE`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `paciente` */

/*Table structure for table `poblacion` */

DROP TABLE IF EXISTS `poblacion`;

CREATE TABLE `poblacion` (
  `IDPOBLACION` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE_POBLACION` varchar(50) NOT NULL COMMENT 'NOMBRE DE LA POBLACION',
  PRIMARY KEY (`IDPOBLACION`),
  UNIQUE KEY `PRIMARIO_POBLACION` (`IDPOBLACION`),
  KEY `NOMBRE_POBLACION` (`NOMBRE_POBLACION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `poblacion` */

/*Table structure for table `telefono` */

DROP TABLE IF EXISTS `telefono`;

CREATE TABLE `telefono` (
  `IDTELEFONO` int(11) NOT NULL,
  `Telefono` varchar(45) NOT NULL,
  `IDPACIENTE` int(11) NOT NULL,
  PRIMARY KEY (`IDTELEFONO`),
  UNIQUE KEY `PRIMARIO_TELEFONO` (`IDTELEFONO`),
  UNIQUE KEY `TELEFONOS` (`Telefono`),
  KEY `fk_Telefono_PACIENTE1_idx` (`IDPACIENTE`),
  CONSTRAINT `fk_Telefono_PACIENTE1` FOREIGN KEY (`IDPACIENTE`) REFERENCES `paciente` (`IDPACIENTE`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `telefono` */

/*Table structure for table `tipo_paciente` */

DROP TABLE IF EXISTS `tipo_paciente`;

CREATE TABLE `tipo_paciente` (
  `IDTIPO_PACIENTE` int(11) NOT NULL AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DE LA TABLA',
  `TIPO_PACIENTE` varchar(20) NOT NULL COMMENT 'TIPO DEL PACIENTE, A=ASEGURADO, P=PARTICULAR',
  PRIMARY KEY (`IDTIPO_PACIENTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `tipo_paciente` */

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
